test: main.cpp
	arm-linux-gnueabihf-g++ -march=armv6zk -mtune=arm1176jzf-s -mfpu=vfp -mfloat-abi=hard -Ofast -Wall -pthread  -I/usr/local/include/RF24/ -I../.. -L/usr/local/lib main.cpp -lrf24 -o main
